# Generated by Django 3.0.5 on 2020-04-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0002_catlog_1st_level_catlog_2nd_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='catlog_1st_level',
            old_name='Topic',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='catlog_2nd_level',
            old_name='Topic',
            new_name='Cats',
        ),
    ]
