# Generated by Django 3.0.5 on 2020-04-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0003_auto_20200427_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catlog_1st_Level',
            new_name='Catlog',
        ),
        migrations.AlterModelOptions(
            name='catlog',
            options={'verbose_name_plural': 'catlog'},
        ),
        migrations.DeleteModel(
            name='Catlog_2nd_Level',
        ),
    ]
