# Generated by Django 3.0.5 on 2020-05-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0006_auto_20200502_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'article'},
        ),
    ]
