# Generated by Django 3.0.5 on 2020-05-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0008_auto_20200502_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catlog',
            options={},
        ),
    ]
