# Generated by Django 3.0.5 on 2020-05-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0009_auto_20200503_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='topic',
            new_name='catlog',
        ),
    ]
