# Generated by Django 3.0.5 on 2020-05-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0010_auto_20200503_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
