# Generated by Django 3.0.5 on 2020-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0011_article_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
