# Generated by Django 3.0.5 on 2020-05-05 15:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0012_auto_20200504_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
