# Generated by Django 3.0.5 on 2020-05-08 05:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0014_remove_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Contents'),
        ),
    ]
