# Generated by Django 3.0.5 on 2020-05-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0015_auto_20200508_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media', verbose_name='cover'),
        ),
    ]
