# Generated by Django 3.0.5 on 2020-05-09 09:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greened_blog', '0016_article_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
